version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - JWT_SECRET=your-super-secret-jwt-key-for-development-only
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:5173
    
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000/api
      - VITE_BACKEND_URL=http://localhost:4000
    depends_on:
      - backend
